defaults:

  scope:
   path: ""
   type: "pages"
  values:
   layout: "project"
   author: "ӯӯ"

# Site settings
title: Ying Ying's home
email: xzffwy@163.com
description: "If you have a job,"                    
description1: "you need to do is,"
description2: "do it,"
description3: "even if you don't like,"
description4: "you have to prove to someone that you have the ability to do one thing,"
description5: "Others will give you a chance!"

url: "xzffwy.github.com"
blog: old blog
github_username: xzffwy 



# Build settings
markdown: kramdown
permalink: pretty
