defaults:

  scope:
   path: ""
   type: "pages"
  values:
   layout: "project"
   author: "ӯӯ"

# Site settings
title: Ying Ying's New World 
email: xzffwy@163.com
description: Just Be Yourself!

url: "xzffwy.github.com"
blog: old blog
github_username: xzffwy



# Build settings
markdown: kramdown
permalink: pretty

#homepage
menu1: Homepage
menu2: Blog
