defaults:

  scope:
   path: ""
   type: "pages"
  values:
   layout: "project"
   author: "盈盈"

# Site settings
title: Ying Wang 
email: xzffwy@163.com
description: Just Be Yourself!

url: "xzffwy.github.com"
blog: old blog
github_username: xzffwy



# Build settings
markdown: kramdown
md: kramdown
#permalink
permalink: pretty

#homepage
menu1: Homepage
menu2: Blog

#coding
encoding: utf-8

